fixtures:
  repositories:
    'apt':
      repo: 'git://github.com/puppetlabs/puppetlabs-apt.git'
      ref: '2.2.2'
    'rpmkey':
      repo: 'git://github.com/stschulte/puppet-rpmkey.git'
      ref: 'v1.0.3'
    'stdlib':
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    yumrepo:
      repo: 'git://github.com/puppetlabs/puppetlabs-yumrepo_core.git'
      ref: '1.0.1'
      puppet_version: ">= 6.0.0"
    zypprepo:
      repo: 'git://github.com/voxpupuli/puppet-zypprepo.git'
      ref: 'v2.2.2'
  symlinks:
    swrepo: "#{source_dir}"
