name 'jwennerberg-swrepo'
version '0.2.0'
source 'git://github.com/jwennerberg/puppet-module-swrepo.git'
author 'jwennerberg'
license 'Apache License, Version 2.0'
summary 'Manage software repositories'
description 'Manage software repositories'
project_page 'https://github.com/jwennerberg/puppet-module-swrepo'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
