name 'jwennerberg-swrepo'
version '0.1.0'
source 'git://github.com/jwennerberg/puppet-module-swrepo.git'
author 'jwennerberg'
license 'Apache License, Version 2.0'
summary 'put a summary here'
description 'put a description here'
project_page 'https://github.com/jwennerberg/puppet-module-swrepo'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
